### ISSUE TITLE
Creating a course page

### ISSUE THREAD

**Issue by karthikr223** [cs130-w21/9#10]
## User Story
As a course creator I want to be able to click create a course to open a page to paste links to the course's content.

## Detailed Description
From the home page, a button click should open a new page which displays the creator name, as well as the option to add a title. This page should be accessible from the course creator's home page.

## Acceptance Criteria

- [ ] When the create course button is clicked from the home page, the course title is requested from the creator.
- [ ] When the course title is provided, a new page is created with the course title at the top.
- [ ] After the new course is created, it should be accessible from the creator's list of courses.

## Tasks
- [x] Create new component on react for the page #51  
- [x] Add Node.js and express functionality to create new course #50  
- [x] Create editable inputs for new course contents #53
- [x] Add function in model to call express route(s) needed to create course #54
- [x] Add model calls to the UI #55
