### ISSUE TITLE
Individual course page with course contents

### ISSUE THREAD

**Issue by martingasparyan** [cs130-w21/9#12]
## User Story
As a course viewer I want to be able to click on a course to see all the links associated with that course.

## Detailed Description
When the user accesses a course, the other sources that are similar and represent content that the user wishes to learn will be displayed as well. 

## Acceptance Criteria
- [x] Given clicking on a single course, then multiple sources in the form of links should be displayed for the user to see in the correct order.

## Task List
- [x] Create and style Individual course page with course title and list #23 
- [x] Make links clickable #22 
- [x] Add react router to application and create route for homepage and course page #24 
- [x] Add functions in model class to allow for fetch of course data #65 
- [x] Add calls from front end to model to fetch the data #66
