### ISSUE TITLE
Creation of courses for others to view

### ISSUE THREAD

**Issue by dbreon88** [cs130-w21/9#3]
## Epic
An ability to create a new course and then add the associated links to the course. Any site visitor can then view this public course and its links. 

## User Stories
- [x] [As a course creator I want to be able to click create a course to open a page to paste links to the courses content](https://github.com/cs130-w21/9/issues/10) 
- [x] [As a course creator I want to be able to paste links into the course creation page and then save the course](https://github.com/cs130-w21/9/issues/8)
- [x] [As a course creator I want to be able to add a description to the course](https://github.com/cs130-w21/9/issues/11)
