### ISSUE TITLE
UML Diagrams

### ISSUE THREAD

**Issue by grantrbrts** [cs130-w21/9#36]
## User Story
As a **team member**, I would like **to see an overview of the application** so that **the member can easily understand.**.

## Detailed Description
Implement UML diagrams.

## Acceptance Criteria
- [x] Finished **[Activity diagram]** #34 
- [x] Finished **[Sequence diagram]** #38 
- [x] Finished **[Class diagram]**  #39 
- [x] Finished **[State Machine diagram]** #35 
- [x] Finished **[Use Case diagram]** #37

**Comment by dbreon88** [comment]
Done. subject to change if needed
