### ISSUE TITLE
Separation of user roles

### ISSUE THREAD

**Issue by dbreon88** [cs130-w21/9#4]
## Epic
Create separate user roles as a site visitor versus someone signed into the site. Logged in users can create courses, add comments and ratings to course. Users not logged in can only view courses. 

## User Stories
- [ ] [As as a course creator i want to be able to log in to create and edit a course](https://github.com/cs130-w21/9/issues/5)
- [ ] [As a course viewer I want to be able to comment on a course](https://github.com/cs130-w21/9/issues/9)
- [ ] [As a course viewer I want to be able to rate a course](https://github.com/cs130-w21/9/issues/6)

**Comment by grantrbrts** [comment]
Didn't get to.
