### ISSUE TITLE
Write documentation for codebase 

### ISSUE THREAD

**Issue by dbreon88** [cs130-w21/9#46]
## User Story
As a Developer, I would like detailed code documentation so that I can easily refer to the docs to understand the application.

## Detailed Description
Write detailed documentation on each of our main notable files. This documentation should detail the purpose of the file/class, explanations of code and functions, and other explanations of any complex parts of the code. It should also note important interactions with other parts in the code base. This documentation is subject to change as the application evolves and will be updated. 

## Acceptance Criteria
- [ ] Given I am looking at a complex file, then I can open the documentation related to that file
- [ ] Given I am looking at the documentation for a given file, then I should be able to fully understand the file and its complexities.

## Tasks
- [ ] Write documentation for server.js
- [ ] Write documentation for routes/course.js
- [ ] Write documentation for routes/user.js
