### ISSUE TITLE
Home Page Display

### ISSUE THREAD

**Issue by martingasparyan** [cs130-w21/9#7]
## User Story
As a course viewer I want to enter the home page and see a list of all the courses.

## Detailed Description
Upon entering the home page of the Desktop Application, the user will be faced with a home page that will suggest the various courses the user can choose from for learning a particular topic. 

## Acceptance Criteria
- [x] When a user accesses the application, then the user should be directed to the home page
- [ ] When a user enters the App, then a list of courses should appear to select from.

## Task List 
- [x] Initialize React Framework #13 
- [x] Create Front Page List Landing Page #15 
- [x] Set up Node.JS Instance #14 
- [x] Set up Express Middleware #19 
- [x] Create Firebase Project #17 
- [x] Create Firebase FireStore instance and create Schema 
- [x] Add dummy data to Firestore and load into list on front page #20
