### ISSUE TITLE
Edit Course functionality

### ISSUE THREAD

**Issue by grantrbrts** [cs130-w21/9#8]
## User Story
As a **course creator**, I would like **to be able to edit one of my courses** so that **I can update its contents.**.

## Detailed Description
Course creators should be able to click on a course they previously created to edit its contents. Then save the newly edited contents. 

## Acceptance Criteria
- [ ] Given **I am on the course edit page**, then **I should be able to edits different course elements and then hit save to save the edits to the course.**

## Tasks 
- [x] Add buttons to edit a course from the home page #56 
- [x] Add front end call to model to fetch courses contents when edit button is selected on a certain course #57
